In [1]:
# Load packages and settings
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.min_rows', 50)
import seaborn as sns


import matplotlib.pyplot as plt
%matplotlib widget
plt.rcParams['figure.figsize'] = (12,8)
plt.rcParams["image.cmap"] = "tab10"
plt.rcParams['axes.prop_cycle'] = plt.cycler(color=plt.cm.tab10.colors)
fs_label = 16
parameters = {
                'axes.labelsize': fs_label,
                'axes.titlesize': fs_label+4,
                'xtick.labelsize': fs_label,
                'ytick.labelsize': fs_label, 
                'legend.fontsize': fs_label, 
                'lines.markersize': 10,
                'lines.linewidth': 3
             }
plt.rcParams.update(parameters)
%matplotlib widget
from matplotlib import cm # Colormaps
import matplotlib.colors as colors
# cmap = plt.cm.get_cmap('Dark2',len(ageGroups))

import locale
import matplotlib.dates as mdates
locale.setlocale(locale.LC_ALL, '') 
locale.setlocale(locale.LC_TIME,"Danish")
# ax1.xaxis.set_major_formatter(mdates.DateFormatter('%b\n%Y'))
# ax1.spines['top'].set_visible(False) 

import os
# import csv
import math

import datetime
from datetime import date


# ax.legend(bbox_to_anchor=(1.04,0.5), loc="center left")

saveFigures = True
# saveFigures = False
print('saveFigures is set to: '+str(saveFigures))

print('Done loading packages')

# Define running mean functions
def rnMean(data,meanWidth):
    return np.convolve(data, np.ones(meanWidth)/meanWidth, mode='valid')
def rnTime(t,meanWidth):
    return t[math.floor(meanWidth/2):-math.ceil(meanWidth/2)+1]

saveFigures is set to: True
Done loading packages


In [7]:
# Define paths
rootdir_data = os.getcwd() +"\\..\\DanskeData\\" 

path_data = rootdir_data + "ssi_data\\"
path_dash = rootdir_data + "ssi_dashboard\\"
path_vacc = rootdir_data + "ssi_vacc\\"
path_figs = os.getcwd() +"\\..\\Figures\\" 

# path_figs = path_figs + "Immunity_SSI\\"

In [15]:
latestsubdir = list(os.walk(path_dash))[0][1][-1]
latestdir = path_dash + latestsubdir
df = pd.read_csv(latestdir+'/Regionalt_DB/18_fnkt_alder_uge_testede_positive_nyindlagte.csv',encoding='latin1',delimiter = ';')

df['Nyindlagte pr. 100.000 borgere'] = pd.to_numeric(df['Nyindlagte pr. 100.000 borgere'].str.replace(',','.'))

# df_07['Dato'] = pd.to_datetime(df_07['Dato'])
df.tail()

Uge Aldersgruppe  Testede pr. 100.000 borgere  \
926  2022-W05        16-19                        16112   
927  2022-W05        20-39                        19708   
928  2022-W05        40-64                        23119   
929  2022-W05        65-79                        10226   
930  2022-W05          80+                        11687   

     Positive pr. 100.000 borgere  Nyindlagte pr. 100.000 borgere  \
926                          6224                            24.4   
927                          5266                            36.5   
928                          4640                            28.6   
929                          1887                            45.9   
930                          1220                           118.8   

     Antal testede  Antal positive  
926          44171           17063  
927         293318           78379  
928         436752           87649  
929          92423           17051  
930          34123            3563

In [23]:
weekShort = df.Uge.apply(lambda x: x[-2:])
# dfDate
df['Date'] = df.Uge.apply(lambda x: datetime.datetime.strptime(x + '-1', "%Y-W%W-%w"))

In [27]:
curdf = df[df.Aldersgruppe == '00-02']
curdf.tail()

Uge Aldersgruppe  Testede pr. 100.000 borgere  \
886  2022-W01        00-02                         6834   
895  2022-W02        00-02                        12228   
904  2022-W03        00-02                        14563   
913  2022-W04        00-02                        11454   
922  2022-W05        00-02                         9508   

     Positive pr. 100.000 borgere  Nyindlagte pr. 100.000 borgere  \
886                          1369                            37.6   
895                          2591                            56.9   
904                          3463                            84.2   
913                          3208                            79.4   
922                          3258                            96.0   

     Antal testede  Antal positive       Date  
886          12738            2551 2022-01-03  
895          22790            4829 2022-01-10  
904          27143            6455 2022-01-17  
913          21349            5979 2022-01-24  
922          17726            6073 2022-01-31

In [48]:
# curAdmCount

In [98]:
curAdm = curdf['Nyindlagte pr. 100.000 borgere']
curCase = curdf['Antal positive']
curInci = curdf['Positive pr. 100.000 borgere']
curPopCount = np.mean((100000*curCase/curInci)[-5:])
curPopCount 

curAdmCount = curPopCount*curAdm/100000

fig,allAxes = plt.subplots(2,1,sharex=True,figsize=(13,12))
# ax1,ax2,ax3 = allAxes.flatten()
ax1,ax2 = allAxes.flatten()

ax1.plot(curdf.Date,curAdm,'k.-')
ax1_2 = ax1.twinx()
ax1_2.plot(curdf.Date,curAdmCount,'k.-')

# ax1.set_ylabel('Nyindlæggelser per 100.000')
# ax1_2.set_ylabel('Antal nyindlæggelser')
ax1.set_ylabel('New admissions per 100.000')
ax1_2.set_ylabel('New admissions')

ax1.set_ylim(bottom=0)
ax1_2.set_ylim(bottom=0)

ax2.plot(curdf.Date,curdf['Positive pr. 100.000 borgere'],'k.-')
ax2_2 = ax2.twinx()
ax2_2.plot(curdf.Date,curdf['Antal positive'],'k.-')

ax2.set_ylabel('Cases per 100.000')
ax2_2.set_ylabel('Cases')
ax2.set_ylim(bottom=0)
ax2_2.set_ylim(bottom=0)

ax1.grid(axis='y')
ax2.grid(axis='y')

ax1.set_title('0 to 2 year olds')

if saveFigures:
    fig.savefig(path_figs+'CasesAndHospitalizations_Full_0-2')

ax1.set_xlim(left=np.datetime64('2021-09-01'))


if saveFigures:
    fig.savefig(path_figs+'CasesAndHospitalizations_0-2')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [93]:
# print(curAdmCount[:-1].values/curCase[1:].values)
# print(curAdmCount.values/curCase.values)
print(curCase.values[-5:])
print(curAdmCount.values[-5:])
print(curCase[2:].values[-5:])
print(curAdmCount[:-2].values[-5:])

[2551 4829 6455 5979 6073]
[ 70.0785712  106.04975269 156.93126848 147.9850679  178.92401156]
[2551 4829 6455 5979 6073]
[ 40.07152342  79.21115095  70.0785712  106.04975269 156.93126848]


In [101]:
caseHosp = curAdmCount/curCase
caseHospm1 = curAdmCount[1:].values/curCase[:-1].values
caseHospm2 = curAdmCount[2:].values/curCase[:-2].values

fig,ax1 = plt.subplots()
ax1.plot(curdf.Date,caseHosp,'k.:',markersize=2,linewidth=0.5,label='Admission divided by cases (same week)')
ax1.plot(rnTime(curdf.Date,7),rnMean(caseHosp,7),'k',label='7-day running mean')
ax1.plot(curdf.Date[:-1],caseHospm1,'r.:',markersize=2,linewidth=0.5,label='Admission divided by cases (week earlier)')
ax1.plot(rnTime(curdf.Date[:-1],7),rnMean(caseHospm1,7),'r',label='7-day running mean')
ax1.plot(curdf.Date[:-2],caseHospm2,'b.:',markersize=2,linewidth=0.5,label='Admission divided by cases (two weeks earlier)')
ax1.plot(rnTime(curdf.Date[:-2],7),rnMean(caseHospm2,7),'b',label='7-day running mean')

ax1.set_ylim(bottom=0)
ax1.set_ylim(top=0.4)

ax1.legend(loc='upper right',fontsize=13)
ax1.grid()

ax1.set_ylabel('Case hospitalization rate')
ax1.set_title('0 to 2 year olds')

if saveFigures:
    fig.savefig(path_figs+'CaseHospitalization_Full_0-2')

ax1.set_ylim(top=0.14)
ax1.set_xlim(left=np.datetime64('2021-09-01'))
if saveFigures:
    fig.savefig(path_figs+'CaseHospitalization_0-2')

<ipython-input-101-a7fa0f04c618>:2: RuntimeWarning: divide by zero encountered in true_divide
  caseHospm1 = curAdmCount[1:].values/curCase[:-1].values
<ipython-input-101-a7fa0f04c618>:2: RuntimeWarning: invalid value encountered in true_divide
  caseHospm1 = curAdmCount[1:].values/curCase[:-1].values
<ipython-input-101-a7fa0f04c618>:3: RuntimeWarning: divide by zero encountered in true_divide
  caseHospm2 = curAdmCount[2:].values/curCase[:-2].values
<ipython-input-101-a7fa0f04c618>:3: RuntimeWarning: invalid value encountered in true_divide
  caseHospm2 = curAdmCount[2:].values/curCase[:-2].values


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [5]:
# # Collect age-specific cases for all municipalities
# allSubDirs = list(os.walk(path_dash))[0][1]

# df = pd.DataFrame()

# for curSubDir in allSubDirs:
#     curdir = path_dash + curSubDir
#     curfilepath = curdir+'/Regionalt_DB/21_noegletal_pr_region_pr_fnkt_alder.csv'

#     # Check if file was included at the time. The "Kommune/17" file wasn't included until 2021-09-22 
#     if os.path.isfile(curfilepath):
#         curdf = pd.read_csv(curfilepath,encoding='latin1',delimiter = ';')
        
#         df = pd.concat([df,curdf])

# df
# # # Set dtypes
# # df.Kommune = df.Kommune.fillna(0)  # All NaN kommuner is set to zero
# # df['Kommune'] = df['Kommune'].astype(int)
# # df['Dagsdato'] = pd.to_datetime(df['Dagsdato'])
# # df['Bekræftede tilfælde'] = pd.to_numeric(df['Bekræftede tilfælde'])
# # df['Aldersgruppe'] = df.Aldersgruppe.replace('00-02','0-2')
# # df['Aldersgruppe'] = df.Aldersgruppe.replace('03-05','3-5')
# # df['Aldersgruppe'] = df.Aldersgruppe.replace('06-11','6-11')

# # # df['Forskel'] = df['Bekræftede tilfælde'].diff().fillna(0).astype(int,errors='ignore')

Region Aldersgruppe  Bekræftede tilfælde  \
0           NaN          0-2                   30   
1   Hovedstaden          0-2                 2608   
2   Midtjylland          0-2                  943   
3   Nordjylland          0-2                  375   
4      Sjælland          0-2                  537   
5    Syddanmark          0-2                  828   
6           NaN          3-5                   22   
7   Hovedstaden          3-5                 3700   
8   Midtjylland          3-5                 1382   
9   Nordjylland          3-5                  503   
10     Sjælland          3-5                  841   
11   Syddanmark          3-5                 1274   
12          NaN         6-11                   92   
13  Hovedstaden         6-11                12812   
14  Midtjylland         6-11                 4608   
15  Nordjylland         6-11                 1624   
16     Sjælland         6-11                 3019   
17   Syddanmark         6-11                 3886   
18          NaN        12-15                   67   
19  Hovedstaden        12-15                 9593   
20  Midtjylland        12-15                 4044   
21  Nordjylland        12-15                 1578   
22     Sjælland        12-15                 3063   
23   Syddanmark        12-15                 3265   
24          NaN        16-19                   83   
..          ...          ...                  ...   
30   Syddanmark        16-19                30384   
31          NaN        20-39                 6321   
32  Hovedstaden        20-39               256456   
33  Midtjylland        20-39               130058   
34  Nordjylland        20-39                51816   
35     Sjælland        20-39                70614   
36   Syddanmark        20-39               103116   
37          NaN        40-64                 4450   
38  Hovedstaden        40-64               219605   
39  Midtjylland        40-64               115910   
40  Nordjylland        40-64                49732   
41     Sjælland        40-64                86330   
42   Syddanmark        40-64               106156   
43          NaN        65-79                  353   
44  Hovedstaden        65-79                35835   
45  Midtjylland        65-79                19410   
46  Nordjylland        65-79                 9681   
47     Sjælland        65-79                16392   
48   Syddanmark        65-79                19299   
49          NaN          80+                  135   
50  Hovedstaden          80+                10337   
51  Midtjylland          80+                 4240   
52  Nordjylland          80+                 2270   
53     Sjælland          80+                 3916   
54   Syddanmark          80+                 4417   

    Indlagte på intensiv afdeling  Indlagte        Dato  
0                               0         5  22/09/2021  
1                               0       136  22/09/2021  
2                               0        27  22/09/2021  
3                               0        11  22/09/2021  
4                               0        33  22/09/2021  
5                               0        21  22/09/2021  
6                               0         0  22/09/2021  
7                               0        14  22/09/2021  
8                               0         7  22/09/2021  
9                               0         3  22/09/2021  
10                              0         2  22/09/2021  
11                              0         4  22/09/2021  
12                              0         1  22/09/2021  
13                              1        37  22/09/2021  
14                              0         8  22/09/2021  
15                              0         6  22/09/2021  
16                              0         6  22/09/2021  
17                              0         7  22/09/2021  
18                              0         0  22/09/2021  
19                              0        43  22/09/2021  
20                              0 